# Generated by Django 2.2.28 on 2022-12-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='項目ID')),
                ('name', models.CharField(max_length=255, verbose_name='項目名')),
                ('amount', models.FloatField(max_length=255, verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='項目ID')),
                ('name', models.CharField(max_length=255, verbose_name='項目名')),
                ('amount', models.FloatField(max_length=255, verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
            ],
            options={
                'verbose_name': 'income',
                'verbose_name_plural': 'incomes',
            },
        ),
    ]
