# Generated by Django 2.2.28 on 2022-12-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_auto_20221223_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
