# Generated by Django 2.2.28 on 2022-12-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.FloatField(max_length=255, verbose_name='税込価格')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('date', models.DateField(verbose_name='取得日')),
                ('shop', models.CharField(max_length=255, verbose_name='店舗名')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
