# Generated by Django 2.2.28 on 2022-12-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='date',
            new_name='item_date',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='shop',
            new_name='item_shop',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='url',
            new_name='item_url',
        ),
    ]
