# Generated by Django 2.2.28 on 2022-12-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20221219_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_shop',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_url',
            new_name='url',
        ),
    ]
