# Generated by Django 2.2.28 on 2022-12-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_salefavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salefavorite',
            options={'verbose_name': 'favorite', 'verbose_name_plural': 'favorites'},
        ),
    ]
