# Generated by Django 2.2.28 on 2022-12-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20221223_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='取得日'),
        ),
    ]
